name: Pytest Coverage
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  run_pytest_coverage:
    runs-on: ubuntu-latest
    name: Run Pytest Coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[dev]

      - name: Run pytest-cov
        run: |
          pytest --cov=src/uwtools/ --cov-fail-under=5 --cov-report=html:cov_html

      - name: Display structure of downloaded files
        run: ls -R

      - name: Deploy Coverage Reports to GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./cov_html
          target-folder: ./coverage
